import { SignPdf } from "./SignPdf"


function App() {
  const dynamicHtml = {
    title: 'My Dynamic PDF',
    listItems: ['Item 1', 'Item 2', 'Item 3'],
    independentContractorText: 'Independent Consultant',
    signatureImg: 'base64 encoded image data',
    signatureDate: '2024-05-28',
    footerText: 'Generated by React PDF',
  };
  return (
    <>
      <SignPdf dynamicHtml={dynamicHtml}/>
    </>
  )
}

export default App
