import { SignPdf } from "./SignPdf"
import logoM from "./assets/images/logo.jpeg"
import { DynamicPdfHtml } from "./components/ViewPdf/PdfView";

function App() {
  const dynamicHtml: DynamicPdfHtml = {
    title: 'Non-Disclosure Agreement',
    listItems: ["Confidential Information means any and all information disclosed by the Disclosing Party to the Receiving Party, whether orally, in writing, or by any other means, that is not already known to the Receiving Party or generally known to the public domain, and includes, but is not limited to, [List specific types of confidential information, e.g., trade secrets, customer lists, marketing plans, etc.", 
    'The Receiving Party agrees to hold in confidence and not to disclose, use, or reproduce any Confidential Information of the Disclosing Party to any third party without the prior written consent of the Disclosing Party. The Receiving Party will use the same degree of care to protect the Confidential Information as it uses to protect its own confidential information, but in no event less than a reasonable degree of care',
    'The Receiving Party will not be obligated to keep Confidential Information confidential to the extent such information',
    'This Agreement shall be effective as of the date first written above and shall remain in full force and effect for a period of [Number] years from the date of disclosure of the Confidential Information (the "Term").'],
    independentContractorText: 'Independent Consultant',
    signatureImg: 'base64 encoded image data',
    signatureDate: '2024-05-28',
    footerText: 'Generated by React PDF',
    logo: logoM,
    class:{
      container:'container'
    }
  };
  return (
    <>
      <SignPdf dynamicHtml={dynamicHtml}/>
    </>
  )
}

export default App
